### ISSUE TITLE
请发帖人联系西工大

### ISSUE THREAD

**Issue by dangdang12345** [KirikoXX/Tang#19]
上西工大航天学院问问，他不能保研，那西工大还有能保研的人吗？
校长：汪劲松，党委书记：张玮
附：西工大校长书记信箱，请造谣者实名举报他
https://www.nwpu.edu.cn/xzxx.htm

**Comment by KirikoXX** [comment]
什么叫造谣啊？
我们把他说的话干的事截图记录又发了一遍。
