### ISSUE TITLE
Dear friend, may you delete file #018 of the repo?

### ISSUE THREAD

**Issue by nikenike123** [KirikoXX/Tang#20]
Dear friend 

The #018 file of the repo has personal private information that may lead to ambiguous understanding. 
I sincerely know that it is a pity that such a psychopath has bothered and disturbed many people, which may disrupt their daily schedule, since I also trouble by the wicked and vicious asshole. Please delete the #018 file, which includes private information of related person. 

And after you delete that, please by the way delete the issue, also. Remeber stay away from virus like psychopath. Hope you can do as I suggest.  Thank you.

**Comment by nikenike123** [comment]
At least cover the mask over the name of related people in the #018 file of the repo

**Comment by KirikoXX** [comment]
Problem fixed.
But I must tell you that, thiese infomation can still be seen from commit history and repos forked by others.
