### ISSUE TITLE
Hi，I mean the first picture of the file #018 that has the information about name of troubled person. Thank you  

### ISSUE THREAD

**Issue by nikenike123** [KirikoXX/Tang#21]

**Comment by nikenike123** [comment]
please cover the mask or just delete it. No infomation of the name dose not hinder disclosing the freak

**Comment by nikenike123** [comment]
I DO NOT WORRY ABOUT OTHERS WHO ALSO FORK THE REPO, SINCE YOURS IS THE SOURCE AND MOST AVAILABEL FROM GOOGLE SEARCH.

**Comment by nikenike123** [comment]
May you delete or just blur the name of the pic 1? Thank you. By the way after fix the problem delete the issue

**Comment by KirikoXX** [comment]
Sorry I didn't notice the name in massage box. Problem fixed.
Have a nice day XD
